apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: nginx-test
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

  